/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp | null>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp | null>;
  userId: string;
}

export interface Companies {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  website: string | null;
}

export interface Contacts {
  companyId: number | null;
  createdAt: Generated<Timestamp | null>;
  email: string | null;
  firstName: string | null;
  id: Generated<number>;
  lastName: string | null;
  phone: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface Deals {
  companyId: number | null;
  contactId: number | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  stage: Generated<string>;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  value: Numeric | null;
}

export interface Files {
  createdAt: Generated<Timestamp | null>;
  etag: string | null;
  filename: string;
  id: Generated<string>;
  metadata: Json | null;
  mimeType: string;
  size: Int8;
  status: Generated<string>;
  updatedAt: Generated<Timestamp | null>;
  updatedByUserId: string | null;
}

export interface Session {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp | null>;
  userAgent: string | null;
  userId: string;
}

export interface Todos {
  completed: Generated<boolean>;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp | null>;
  email: string | null;
  emailVerified: Generated<boolean | null>;
  id: string;
  image: string | null;
  name: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface Verification {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp | null>;
  value: string;
}

export interface DB {
  account: Account;
  companies: Companies;
  contacts: Contacts;
  deals: Deals;
  files: Files;
  session: Session;
  todos: Todos;
  user: User;
  verification: Verification;
}
